// Generated by gencpp from file nubot_common/ShootRequest.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_SHOOTREQUEST_H
#define NUBOT_COMMON_MESSAGE_SHOOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nubot_common
{
template <class ContainerAllocator>
struct ShootRequest_
{
  typedef ShootRequest_<ContainerAllocator> Type;

  ShootRequest_()
    : strength(0)
    , ShootPos(0)  {
    }
  ShootRequest_(const ContainerAllocator& _alloc)
    : strength(0)
    , ShootPos(0)  {
  (void)_alloc;
    }



   typedef int64_t _strength_type;
  _strength_type strength;

   typedef int64_t _ShootPos_type;
  _ShootPos_type ShootPos;





  typedef boost::shared_ptr< ::nubot_common::ShootRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_common::ShootRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShootRequest_

typedef ::nubot_common::ShootRequest_<std::allocator<void> > ShootRequest;

typedef boost::shared_ptr< ::nubot_common::ShootRequest > ShootRequestPtr;
typedef boost::shared_ptr< ::nubot_common::ShootRequest const> ShootRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_common::ShootRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_common::ShootRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nubot_common::ShootRequest_<ContainerAllocator1> & lhs, const ::nubot_common::ShootRequest_<ContainerAllocator2> & rhs)
{
  return lhs.strength == rhs.strength &&
    lhs.ShootPos == rhs.ShootPos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nubot_common::ShootRequest_<ContainerAllocator1> & lhs, const ::nubot_common::ShootRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nubot_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nubot_common::ShootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::ShootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::ShootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::ShootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::ShootRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::ShootRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_common::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e67331c8b47643120ddf7ee7ff01a";
  }

  static const char* value(const ::nubot_common::ShootRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e67331c8b4764ULL;
  static const uint64_t static_value2 = 0x3120ddf7ee7ff01aULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_common::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_common/ShootRequest";
  }

  static const char* value(const ::nubot_common::ShootRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_common::ShootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 strength\n"
"int64 ShootPos\n"
;
  }

  static const char* value(const ::nubot_common::ShootRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_common::ShootRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strength);
      stream.next(m.ShootPos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_common::ShootRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_common::ShootRequest_<ContainerAllocator>& v)
  {
    s << indent << "strength: ";
    Printer<int64_t>::stream(s, indent + "  ", v.strength);
    s << indent << "ShootPos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ShootPos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_SHOOTREQUEST_H
