string robot_name
bool ball_visible
bool obstacle_visible
bool friend_visible
bool[] available
bool set_obstacle # untuk lomba online
geometry_msgs/Pose2D position
geometry_msgs/Pose2D[] teammates
geometry_msgs/Pose2D velocity
geometry_msgs/Point local_friend
geometry_msgs/Point global_friend
geometry_msgs/Point local_ball
geometry_msgs/Point global_ball
geometry_msgs/Point[] local_balls
geometry_msgs/Point[] balls
geometry_msgs/Point[] way_points
Obstacle[] obstacles
Obstacle obstacle1   # untuk lomba online
Obstacle obstacle2   # untuk lomba online
Obstacle kiper_obstacle # untuk lomba online
Point2d[] local_obstacles
Point2d[] global_obstacles